service: esmiercoleshomero-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  profile: jc
  timeout: 900
  httpApi:
    cors: false
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cloudwatch:PutMetricData
          Resource: "*"
  environment:
    ACCESS_TOKEN: ${ssm:/lambda/esmiercoleshomero-bot/accessToken}

custom:
  webpack:
    includeModules:
      forceExclude:
      - "@aws-sdk/client-cloudwatch"

functions:
  run:
    handler: handler.run
    events:
      # Each Wednesday at 10am UTC-3
      - schedule: cron(0 13 ? * MON *)

plugins:
  - serverless-webpack
